//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSqlDisasterRecovery.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DimAccount
    {
        public int AccountKey { get; set; }
        public Nullable<int> ParentAccountKey { get; set; }
        public Nullable<int> AccountCodeAlternateKey { get; set; }
        public Nullable<int> ParentAccountCodeAlternateKey { get; set; }
        public string AccountDescription { get; set; }
        public string AccountType { get; set; }
        public string Operator { get; set; }
        public string CustomMembers { get; set; }
        public string ValueType { get; set; }
        public string CustomMemberOptions { get; set; }
    }
}
