//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSqlDisasterRecovery.DataService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdventureworksDW2016CTP3Entities : DbContext
    {
    public AdventureworksDW2016CTP3Entities(string connectionString) : base(connectionString)
    {
    }
        public AdventureworksDW2016CTP3Entities()
            : base("name=AdventureworksDW2016CTP3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DimAccount> DimAccounts { get; set; }
    }
}
